// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMT4OIZC6xfhvweIsy-cC_3hOcQrlk6H0',
    appId: '1:732541499968:web:d646894b53781223c93da5',
    messagingSenderId: '732541499968',
    projectId: 'sudhaar-43992',
    authDomain: 'sudhaar-43992.firebaseapp.com',
    storageBucket: 'sudhaar-43992.appspot.com',
    measurementId: 'G-LWS872YN44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVCHwENSbMCXW6rg2LjfTfv83X9nr68n8',
    appId: '1:732541499968:android:ef5c359626a5d4fcc93da5',
    messagingSenderId: '732541499968',
    projectId: 'sudhaar-43992',
    storageBucket: 'sudhaar-43992.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY8GG5RWpHAfusduBda0RWUemoSb6wSzE',
    appId: '1:732541499968:ios:f6bf10277e3abab0c93da5',
    messagingSenderId: '732541499968',
    projectId: 'sudhaar-43992',
    storageBucket: 'sudhaar-43992.appspot.com',
    iosBundleId: 'com.example.sudhaar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY8GG5RWpHAfusduBda0RWUemoSb6wSzE',
    appId: '1:732541499968:ios:dcdeb2c119ee8311c93da5',
    messagingSenderId: '732541499968',
    projectId: 'sudhaar-43992',
    storageBucket: 'sudhaar-43992.appspot.com',
    iosBundleId: 'com.example.sudhaar.RunnerTests',
  );
}
